nim = input("Masukkan Nim Anda: ")
nama = input("Masukkan Nama Lengkap: ")
kelas = input("Masukkan Kelas Anda: ")
usia = input("Masukkan Usia: ")
print ("=====================================")
print ("IDENTITAS MAHASISWA")
print ("=====================================")
print ("NIM Mahasiswa :",nim)
print ("Nama Lengkap  :",nama)
print ("Kelas Saat Ini:",kelas)
print ("Usia Anda     :",usia)
print ("====================================")
